export const AJAX = {
  BEGIN:'AJAX_BEGIN',
  ERROR:'AJAX_ERROR',
}

export const CONTACT = {
  DELETE: 'CONTACT_DELETE',
  DETAIL: 'CONTACT_DETAIL',
  INSERT: 'CONTACT_INSERT',
  LIST: 'CONTACT_LIST',
  LOAD: 'CONTACT_LOAD',
  UPDATE: 'CONTACT_UPDATE',
  UPSERT: 'CONTACT_UPSERT'
}

export const EDUCATION = {
  DELETE: 'EDUCATION_DELETE',
  DETAIL: 'EDUCATION_DETAIL',
  INSERT: 'EDUCATION_INSERT',
  LIST: 'EDUCATION_LIST',
  LOAD: 'EDUCATION_LOAD',
  UPDATE: 'EDUCATION_UPDATE',
  UPSERT: 'EDUCATION_UPSERT'
}

export const EXPERIENCE = {
  DELETE: 'EXPERIENCE_DELETE',
  DETAIL: 'EXPERIENCE_DETAIL',
  INSERT: 'EXPERIENCE_INSERT',
  LIST: 'EXPERIENCE_LIST',
  LOAD: 'EXPERIENCE_LOAD',
  UPDATE: 'EXPERIENCE_UPDATE',
  UPSERT: 'EXPERIENCE_UPSERT'
}

export const HOME = {
  DELETE: 'HOME_DELETE',
  DETAIL: 'HOME_DETAIL',
  INSERT: 'HOME_INSERT',
  LIST: 'HOME_LIST',
  LOAD: 'HOME_LOAD',
  UPDATE: 'HOME_UPDATE',
  UPSERT: 'HOME_UPSERT'
}

export const MESSAGE = {
  DELETE: 'MESSAGE_DELETE',
  DETAIL: 'MESSAGE_DETAIL',
  INSERT: 'MESSAGE_INSERT',
  LIST: 'MESSAGE_LIST',
  LOAD: 'MESSAGE_LOAD',
  UPDATE: 'MESSAGE_UPDATE',
  UPSERT: 'MESSAGE_UPSERT'
}

export const RESUME = {
  DELETE: 'RESUME_DELETE',
  DETAIL: 'RESUME_DETAIL',
  INSERT: 'RESUME_INSERT',
  LIST: 'RESUME_LIST',
  LOAD: 'RESUME_LOAD',
  UPDATE: 'RESUME_UPDATE',
  UPSERT: 'RESUME_UPSERT'
}

export const SITE = {
  DELETE: 'SITE_DELETE',
  DETAIL: 'SITE_DETAIL',
  INSERT: 'SITE_INSERT',
  LIST: 'SITE_LIST',
  LOAD: 'SITE_LOAD',
  UPDATE: 'SITE_UPDATE',
  UPSERT: 'SITE_UPSERT'
}

export const SKILLSET = {
  DELETE: 'SKILLSET_DELETE',
  DETAIL: 'SKILLSET_DETAIL',
  INSERT: 'SKILLSET_INSERT',
  LIST: 'SKILLSET_LIST',
  LOAD: 'SKILLSET_LOAD',
  UPDATE: 'SKILLSET_UPDATE',
  UPSERT: 'SKILLSET_UPSERT'
}

export const SOCIALMEDIA = {
  DELETE: 'SOCIALMEDIA_DELETE',
  DETAIL: 'SOCIALMEDIA_DETAIL',
  INSERT: 'SOCIALMEDIA_INSERT',
  LIST: 'SOCIALMEDIA_LIST',
  LOAD: 'SOCIALMEDIA_LOAD',
  UPDATE: 'SOCIALMEDIA_UPDATE',
  UPSERT: 'SOCIALMEDIA_UPSERT'
}
