export const AJAX = {
  BEGIN:'AJAX_BEGIN',
  ERROR:'AJAX_ERROR',
}

export const ACCOUNT = {
  DELETE: 'ACCOUNT_DELETE',
  DETAIL: 'ACCOUNT_DETAIL',
  EDIT: 'ACCOUNT_EDIT',
  LOGIN: 'ACCOUNT_LOGIN',
  LOGOUT: 'ACCOUNT_LOGOUT'
}

export const CONTACT = {
  INSERT: 'CONTACT_INSERT',
  LOAD: 'CONTACT_LOAD'
}

export const EDUCATION = {
  LOAD: 'EDUCATION_LOAD'
}

export const EXPERIENCE = {
  LOAD: 'EXPERIENCE_LOAD'
}

export const HOME = {
  LOAD: 'HOME_LOAD'
}

export const PROFILE = {
  DELETE: 'PROFILE_DELETE',
  DETAIL: 'PROFILE_DETAIL',
  INSERT: 'PROFILE_INSERT',
  LIST: 'PROFILE_LIST',
  LOAD: 'PROFILE_LOAD',
  UPDATE: 'PROFILE_UPDATE',
  HOME: {
    LOAD: 'PROFILE_HOME_LOAD',
    UPSERT: 'PROFILE_HOME_UPSERT'
  },
  EXPERIENCE: {
    LOAD: 'PROFILE_EXPERIENCE_LOAD',
    UPSERT: 'PROFILE_EXPERIENCE_UPSERT'
  },
  PROJECT: {
    LOAD: 'PROFILE_PROJECT_LOAD',
    UPSERT: 'PROFILE_PROJECT_UPSERT',
    DELETE: 'PROFILE_PROJECT_DELETE'
  },
  SKILL: {
    LOAD: 'PROFILE_SKILL_LOAD',
    UPSERT: 'PROFILE_SKILL_UPSERT'
  }
}

export const RESUME = {
  LOAD: 'RESUME_LOAD'
}

export const SITE = {
  LOAD: 'SITE_LOAD'
}

export const SKILLSET = {
  LOAD: 'SKILLSET_LOAD'
}

export const SOCIALMEDIA = {
  LOAD: 'SOCIALMEDIA_LOAD'
}

export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';

export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
